name: Dr Header Release Builds
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.5, 3.6, 3.7]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: |
          pip install --upgrade setuptools
          python setup.py test

      - name: Make Egg
        run: |
          python setup.py bdist_egg

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.egg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
