name: Dr Header Release Builds
on: 
  release:
    - prerelease
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.5, 3.6, 3.7]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with pytest
        run: |
          pip install --upgrade setuptools
          python setup.py test

      - name: Make Egg
        run: |
          python setup.py bdist_egg

      - name: Publish Egg
        uses: actions/upload-artifact@master
        with:
          name: DrHeader Egg
          path: dist/*.egg
